name: Compile and Release Resume
on:   
  push:
    tags:
    - '*'
  workflow_dispatch:


permissions:
  contents: write
  packages: read
    
jobs:
  latex:
    defaults:
      run:
        shell: bash
    runs-on: [ubuntu-latest]
    continue-on-error: true
    container:
      image: ghcr.io/${{ github.repository_owner }}/resume/latex:latest
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:  
    - uses: actions/checkout@v4  
    - name: compile
      run: |
        lualatex -interaction=nonstopmode -synctex=1 -file-line-error src/resume.tex || true
    - uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: src/resume.pdf
    - run: |
        ls -la
        echo "event name: ${{ github.event_name }}"
        echo "Github Actions powered automated release [workflow!](https://github.com/mbmcmullen27/Resume/actions/workflows/build.yaml)" >> release.md
        
    - if: ${{ github.event_name == 'push' }}
      run: echo "Triggered by a pushed tag"
    - uses: ncipollo/release-action@v1
      if: 
      with:
        artifacts: "resume.pdf"
        bodyFile: "release.md"
        token: ${{ secrets.GITHUB_TOKEN }}
