  name: Github Action for LaTeX
  on:   
    push:
      tags:
      - '*'
  jobs:
    compile:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: xu-cheng/latex-action@v2
          with:
            root_file: resume.tex
        - uses: actions/upload-artifact@v2
          with:
            name: PDF
            path: resume.pdf
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "PDF"
            bodyFile: "resume.pdf"
            token: ${{ secrets.GITHUB_TOKEN }}
