  name: Github Action for LaTeX
  on:   
    push:
      tags:
      - '*'
    workflow_dispatch:

  jobs:
    compile:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: xu-cheng/latex-action@v2
          with:
            root_file: resume.tex
        - uses: actions/upload-artifact@v2
          with:
            name: PDF
            path: resume.pdf
        - run: |
            echo "event name: ${{ github.event_name }}"
            echo "Github action powered automated release [workflow!](https://github.com/mbmcmullen27/Resume/actions/workflows/build.yaml)" >> release.md
            
        - if: ${{ github.event_name == 'push' }}
          run: echo "Triggered by a pushed tag"
        # - uses: ncipollo/release-action@v1
        #   if: 
        #   with:
        #     artifacts: "resume.pdf"
        #     bodyFile: "release.md"
        #     token: ${{ secrets.GITHUB_TOKEN }}
